BlogPostClient + Web-Api + Client
OpenGeekBrains/Thoughts pull request #32
Opened 2022-06-03 20:37 UTC by nester-a

2022-06-06 11:54 UTC, nester-a commented
Большое количество добавленных файлов связано с созданием DTO-моделей

2022-06-08 17:07 UTC, Infarh requested changes

2022-06-08 17:07 UTC, Infarh commented on Services/Thoughts.Services/Models/CreatePostDTO.cs
> +    public struct CreatePostDTO
```suggestion
    public class CreatePostDTO
```
все DTO-структуры надо переделать в DTO-классы. Иначе система привязки модели ASP.NET Core WebAPI не может их создать и выполнить привязку.

2022-06-08 17:07 UTC, Infarh commented on Services/Thoughts.WebAPI/Controllers/BlogPostController.cs
> +        public async Task<IActionResult> AssignTagAsync([FromBody] PostTagDTO dto, CancellationToken Cancel = default)
```suggestion
        [HttpPut("posts/{PostId}/tag/{Tag}")]
        public async Task<IActionResult> AssignTagAsync([FromRoute] PostTagDTO dto, CancellationToken Cancel = default)
```
Если параметры модели указаны в маршруте, то надо указать системе привязки, что брать их надо не из тела запроса, а из параметров маршрута. Это нужно для Post и Put запросов (которые имеют тело)

2022-06-09 06:18 UTC, nester-a commented on Services/Thoughts.Services/Models/CreatePostDTO.cs
> +    public struct CreatePostDTO
ОК, понял

2022-06-15 18:02 UTC, nester-a commented on Services/Thoughts.Services/Models/CreatePostDTO.cs
> +    public struct CreatePostDTO
исправлено

2022-06-15 18:02 UTC, nester-a commented on Services/Thoughts.WebAPI/Controllers/BlogPostController.cs
> +        public async Task<IActionResult> AssignTagAsync([FromBody] PostTagDTO dto, CancellationToken Cancel = default)
Исправлено

2022-10-19 15:34 UTC, closed without merging