first
OpenGeekBrains/Thoughts pull request #68
Opened 2022-09-26 20:40 UTC by RonzhinLeonid

2022-09-28 16:47 UTC, Infarh requested changes

2022-09-28 16:47 UTC, Infarh commented on Data/Thoughts.DAL.Entities/User.cs
> +    public string PasswordSalt { get; set; }
А соль зачем?

2022-09-28 16:47 UTC, Infarh commented on Common/Thoughts.Domain.Base/Entities/User.cs
> +    public string PasswordHash { get; set; }
Нужно поменять на `IdentityUserId`
Это некий идентификатор пользователя в другой БД

2022-10-04 21:27 UTC, RonzhinLeonid commented on Services/Thoughts.WebAPI/Controllers/Identity/UsersApiController.cs
> +
Возник вопрос, по какому идентификатору искать пользователя в ThoughtsDB.
По идее можно по email, если сделать его обязательным и уникальным в обоих базах

2022-10-04 21:29 UTC, RonzhinLeonid commented on Services/Thoughts.WebAPI/Program.cs
> +    //opt.User.RequireUniqueEmail = false; // ���������� email
Оставляем уникальность email?

2022-10-04 21:29 UTC, RonzhinLeonid commented on Services/Thoughts.WebAPI/Program.cs
> +    opt.Lockout.AllowedForNewUsers = false; // ���������� ����� �������������
Новых пользователей блокируем до подтверждение через email или нам пока это не требуется?

2022-10-04 21:32 UTC, RonzhinLeonid commented on Services/Thoughts.WebAPI/Program.cs
> +//});
Настройка Cookie нужна сейчас?

2022-10-05 15:43 UTC, Infarh commented on Services/Thoughts.WebAPI/Controllers/Identity/UsersApiController.cs
> +
Для сопоставления пользователей в двух БД лучше использовать `UserID : GUID`

2022-10-05 15:44 UTC, Infarh commented on Services/Thoughts.WebAPI/Program.cs
> +    //opt.User.RequireUniqueEmail = false; // ���������� email
Да. Но при регистрации надо заставлять пользователя вводить email. И у Админа надо тоже указывать какой-то ненулевой eMail тоже.

2022-10-05 15:45 UTC, Infarh commented on Services/Thoughts.WebAPI/Program.cs
> +    opt.Lockout.AllowedForNewUsers = false; // ���������� ����� �������������
Пока не требуется. Потом можно будет это вынести в настройки.

2022-10-05 15:45 UTC, Infarh commented on Services/Thoughts.WebAPI/Program.cs
> +//});
Пусть будет. Это не сильно усложнит конфигурирование системы. Что бы потом не вспоминать.

2022-10-12 17:00 UTC, Infarh approved these changes

2022-10-12 17:00 UTC, Infarh commented on Data/Thoughts.DAL.Entities/User.cs
> +    public string IdentityUserId { get; set; }
```suggestion
    public string? IdentityUserId { get; set; }
```

2022-10-12 17:00 UTC, Infarh commented on Data/Thoughts.DAL.SqlServer/Migrations/20220928193818_UpdateUser.cs
> +                nullable: false,
```suggestion
                nullable: true,
```

2022-10-12 17:00 UTC, Infarh commented on Data/Thoughts.DAL.SqlServer/Migrations/20220928193818_UpdateUser.Designer.cs
> +                        .HasColumnType("nvarchar(100)");
```suggestion
                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
```

2022-10-12 17:00 UTC, Infarh commented on Data/Thoughts.DAL.SqlServer/Migrations/ThoughtsDBModelSnapshot.cs
> +                        .HasColumnType("nvarchar(100)");
```suggestion
                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
```

2022-10-12 17:16 UTC, merged